-- LBH Club — World Cup : TIPPING game migration (additive, non-destructive).
-- Paste this whole file into the Supabase SQL Editor and run it ONCE.
--
-- This only ADDS the `tips` table (one row per mate per match). It does NOT
-- touch players / teams / fixtures / picks / settings, so it is safe to run on
-- the live database after the draft is complete.
--
-- ⚠️ Do NOT run supabase-schema.sql on the live DB — that drops every table and
--    would wipe the completed draft. Use this file instead.

create table if not exists tips (
  id          bigint generated by default as identity primary key,
  player_id   integer not null references players(id),
  fixture_id  bigint  not null references fixtures(id) on delete cascade,
  pick        text    not null check (pick in ('home','draw','away')),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now(),
  unique (player_id, fixture_id)        -- one tip per mate per match (enables upsert)
);

-- ---- row level security (open read+write for the shared anon key, like the rest) ----
alter table tips enable row level security;
drop policy if exists "open access" on tips;
create policy "open access" on tips for all using (true) with check (true);
grant all on table tips to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
